import { Roboto } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import profileImage from '../styles/images/me_cover.jpg';
import superBg from '../styles/images/super-bg.jpg';
import Testimonials from './components/Testimonials';

const inter = Roboto({ weight: '400', subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <header>
          <nav className="Navigation">
            <div className="links--left">
              <a href="#" className="logo">
                MM
              </a>

              <a href="#about">About</a>
              <a href="#service">Services</a>
              <a href="#portfolio">Portfolio</a>
            </div>

            <button type="button" className="contact-me">
              {' '}
              Contact Me
            </button>
          </nav>
          <div className="super-bg">
            <Image
              alt="People coding"
              width={1366}
              height={766}
              src={superBg}
            />
          </div>

          <section className="introduction">
            <div className="two-columns">
              <div>
                <h3>I&apos;m Masibulele</h3>
              </div>
              <div>
                <h1>
                  Aspiring <br /> Everything <br /> Engineer
                </h1>
              </div>
              <p>
                Lorem ipsum dolor sit amet consec <br /> tetur adipisicing elit.
                Eaque voluptates porro aliquid?
              </p>

              <div>
                <button type="button" className="btn-work">
                  Let&apos;s Work
                </button>
              </div>
            </div>
            <div className="profile-img">
              <Image className="real-img" src={profileImage} alt="" />
              <Image className="shadow-img" src={profileImage} alt="" />
            </div>
          </section>
        </header>

        <section className="about-me">
          <div className="cv-img">
            <div className="background-box"></div>
            <div className="forefront-box"></div>
            <div className="cv-circle"></div>
          </div>
          <div className="about">
            <h3>About Me</h3>

            <h1>
              Working <br /> With Passion
            </h1>
            <p>
          I am a final year student pursuing a Diploma in ICT Application Development, 
          <br /> I Have a deep passion for technology and innovation. Throughout my academic journey, 
          <br />I've gained a strong foundation in programming languages such as Java,Oracle Apex,VB.Net, MySQL and Python,
          <br /> as well as hands-on experience in developing web pages. I have a keen interest in solving real-world problems through technology, <br />
          i have undertaken some personal projects that have allowed me to apply my knowledge in practical settings. I am a highly motivated and adaptable individual, 
          <br />always eager to learn and explore new challenges in the ever-evolving field of technology.
          <br />My most significant achievement so far has been being a part of a group that developed a Desktop Application for our school Project. <br />
           The App’s purpose was to capture unemployed individuals and old age individuals from rural areas in the Eastern Cape into a database that would be made available to all recruiters across the country. <br />
           This project not only helped improve my technical skills but also taught me the importance of addressing real-world challenges through technology. It was a defining moment in my career, showcasing my ability to lead a team,<br />
            solve complex problems, and create meaningful impact.
            </p>
            <section className="download">
              <button type="button" className="btn-download">
                DOWNLOAD CV
              </button>
            </section>
          </div>
        </section>
        <section className="services">
          <div className="specialties">
            <h3>Services</h3>
            <h2>What Can I Do</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur, <br /> adipisicing elit.
              In ratione dolore itaque.
            </p>
            <section className="my-languages">
              <div className="right-langs">
                <div className="lang1"></div>
                <div className="lang2"></div>
              </div>
              <div className="left-langs">
                <div className="lang3"></div>
                <div className="lang4"></div>
              </div>
            </section>
          </div>
        </section>

        <section className="features">
          <div className="why-me">
            <h3>Features</h3>
            <h2>Why Me?</h2>
          </div>
          <div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br />{' '}
              Voluptatibus deleniti molestias cum veritatis debitis!
            </p>
          </div>
        </section>

        <section className="jobs">
          <div className="job1">
            <p>unique stack</p>
          </div>

          <div className="job2">
            <p> stack overflow</p>
          </div>

          <div className="job3">
            <p>all stacks</p>
          </div>
        </section>

        <div className="my-portfolio">
          <section className="p-headers">
            <h4>My Portfolio</h4>
            <h2>Favourite Projects</h2>
            <h5>I dont know either </h5>
          </section>
          <section className="project-imgs">
            <div className="right-ps">
              <div className="project1"></div>
              <div className="project2"></div>
            </div>
            <div className="left-ps">
              <div className="project3"></div>
              <div className="project4"></div>
            </div>
          </section>

          <section className="btn-prof">
            <button type="button" className="btn-all">
              ALL PORTFOLIO
            </button>
          </section>
        </div>

        <Testimonials />
      </main>
    </>
  );
}
