import Head from "next/head";
import { Inter, Roboto } from "@next/font/google";


const inter = Roboto({ weight: "400", subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>
        <header>
          <nav className="Navigation">
            <img className="LOGO" src="" alt="MM"></img>
           
            <div><a href="#about">About</a> </div>
              <div>  <a href="#service">Services</a></div>
              <div> <a href="#portfolio">Portfolio</a> </div>
              <div><a href="#contact">Contact</a> </div>
            <div> <button className="Contact-me"> Contact Me</button></div>
          <div>
            
          </div>
          </nav>

        <div className="two-columns">
        <h3>I'm Masibulele</h3>
              <h1>Aspiring Everything Engineer</h1>
           
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque
                voluptates porro aliquid?{" "}
              </p>{" "}
              Lorem ipsum dolor sit equisor to now.
              <p />
              <button className="btn-primary">Let's Work</button>
                <img
                  src="IMG_20220819_115032_515.jpg"
                  alt="portfolio picture"/>
         
          </div>

          <div></div>
        </header>

        <section className="about-me">
          <div>
            <img src="" alt="CV-Picture" />
            <h3>About Me</h3>
          </div>
          <h3>
            Working <br /> With Passion
          </h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iusto
            error impedit nostrum aperiam <br /> consequuntur reprehenderit
            nihil id magni numquam harum!
          </p>
          <button className="My Cv">DOWNLOAD CV</button>
        </section>
        <section className="Services">
          <div>
            <h3>Services</h3>
            <h2>What Can I Do</h2>
            <p>
              Lorem ipsum dolor sit amet consectetur, <br /> adipisicing elit.
              In ratione dolore itaque.
            </p>
          </div>
          <div className="squares"></div>
          <div className="circles"></div>
        </section>

        <section className="features">
          <h3>Features</h3>
          <h2>Why Me?</h2>
          <div className="jobs"></div>
        </section>

        <section className="my-portfolio">
          <h4>My Portfolio</h4>
          <h2>Favourite Projects</h2>
          <h5>I dont know either </h5>
          <div className="project1"></div>
          <button className="btn-AllPortfolio">ALL PORTFOLIO</button>
        </section>

        <section className="testimonials">
<h3>Testiompnials</h3>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. <br /> Provident dicta voluptatem porro quam voluptates aperiam in saepe fuga repellat! <br /> Praesentium impedit vel saepe alias doloribus?</p>
        </section>
        
      </body>
    </>
  );
}
